version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/build
      - ./nodemon.json:/nodemon.json
    container_name: ts-node-docker
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm run serve