export {}
describe('Click on tab button', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
  })

  it('click on add tab button', () => {
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="DivTab-0"]').should('be.visible')
    cy.get('[data-testid="DivTab-1"]').should('be.visible')
  })

  it('click on remove tab 2 button', () => {
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="DivTab-0"]').should('be.visible')
    cy.get('[data-testid="DivTab-1"]').should('be.visible')
    cy.get('[data-testid="RemoveTabButton-1"]').click()
    cy.get('[data-testid="DivTab-0"]').should('be.visible')
    cy.should('not.contain', '[data-testid="DivTab-1"]')
  })

  it('click on remove tab 1 button', () => {
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="DivTab-0"]').should('be.visible')
    cy.get('[data-testid="DivTab-1"]').should('be.visible')
    cy.get('[data-testid="RemoveTabButton-0"]').click()
    cy.get('[data-testid="DivTab-0"]').should('be.visible')
    cy.should('not.contain', '[data-testid="DivTab-1"]')
  })

  it('click on add tab button 11 times', () => {
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').should('be.disabled')
    for (let i: number = 1; i < 11; i++) {
      cy.get('[data-testid="DivTab-' + i + '"]').should('be.visible')
    }
    cy.should('not.contain', '[data-testid="DivTab-10"]')
  })

  it('Write scenario in many tab and scenarios are saved', () => {
    cy.wait(1000)
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="DivTab-1"]').should('be.visible')
    cy.get('[data-testid="DivTab-2"]').should('be.visible')
    cy.get('[data-testid="DivTab-0"]').click()
    cy.get('[class="alterationeditor"]').click()
    cy.get('[class="alterationeditor"]').type('hide all_planes at 5 seconds')
    cy.get('[data-testid="DivTab-2"]').click()
    cy.get('[class="alterationeditor"]').click()
    cy.get('[class="alterationeditor"]').type('cut all_planes at 5 seconds')
    cy.get('[data-testid="DivTab-0"]').click()
    cy.contains('hide all_planes at 5 seconds').should('be.visible')
    cy.get('[data-testid="DivTab-2"]').click()
    cy.contains('cut all_planes at 5 seconds').should('be.visible')
  })

  it('Write scenario in many tab and delete tab empty and scenarios are saved', () => {
    cy.wait(1000)
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="DivTab-1"]').should('be.visible')
    cy.get('[data-testid="DivTab-2"]').should('be.visible')
    cy.get('[data-testid="DivTab-0"]').click()
    cy.get('[class="alterationeditor"]').click()
    cy.get('[class="alterationeditor"]').type('hide all_planes at 5 seconds')
    cy.get('[data-testid="DivTab-2"]').click()
    cy.get('[class="alterationeditor"]').click()
    cy.get('[class="alterationeditor"]').type('cut all_planes at 5 seconds')
    cy.get('[data-testid="DivTab-0"]').click()
    cy.contains('hide all_planes at 5 seconds').should('be.visible')
    cy.get('[data-testid="RemoveTabButton-1"]').click()
    cy.get('[data-testid="DivTab-1"]').click()
    cy.contains('cut all_planes at 5 seconds').should('be.visible')
  })

  it('Write scenario in many tab and delete tab with scenario', () => {
    cy.wait(1000)
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.get('[data-testid="DivTab-1"]').should('be.visible')
    cy.get('[data-testid="DivTab-2"]').should('be.visible')
    cy.get('[data-testid="DivTab-0"]').click()
    cy.get('[class="alterationeditor"]').click()
    cy.get('[class="alterationeditor"]').type('hide all_planes at 5 seconds')
    cy.get('[data-testid="DivTab-2"]').click()
    cy.get('[class="alterationeditor"]').click()
    cy.get('[class="alterationeditor"]').type('cut all_planes at 5 seconds')
    cy.get('[data-testid="DivTab-0"]').click()
    cy.contains('hide all_planes at 5 seconds').should('be.visible')
    cy.get('[data-testid="DivTab-2"]').click()
    cy.contains('cut all_planes at 5 seconds').should('be.visible')
    cy.get('[data-testid="RemoveTabButton-2"]').click()
    cy.get('[data-testid="AddTabButton"]').click()
    cy.contains('cut all_planes at 5 seconds').should('not.exist')
  })
})
