openapi: 3.0.0
info:
  title: ALTERATION SCENARIO API
  version: 2.0.0
servers:
  - url: http://localhost:3001
security:
  - ApiKeyAuth: []
paths:
  /recording/alteration:
    post:
      summary: Alter a record
      description: Alter an existing record in the application
      requestBody:
        description: JSON representation of the record to alter
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenario:
                  type: string
                  description: The recording's alteration scenario
                  example: 'hide all_planes at 2 seconds'
                recording:
                  type: object
                  $ref: '#/components/schemas/Recording'
                  description: The record to alter containing a file name and content
                recordingToReplay:
                  type: object
                  $ref: '#/components/schemas/Recording'
                  description: The recording to use for alterer recording containing file name and content in case of replay
                optionsAlteration:
                  type: object
                  $ref: '#/components/schemas/OptionsAlteration'
                  description: Options to apply when altering
              required:
                - scenario
                - recording
                - optionsAlteration
      responses:
        200:
          description: Successfully altered record
          content:
            application/json:
              schema:
                type: object
                properties:
                  alteredRecordings:
                    type: array
                    items:
                      type: object
                      $ref: '#/components/schemas/Recording'
                    description: Altered records in array form
                  error:
                    type: string
                    nullable: true
                    example: null
        422:
          description: Invalid format or syntax error
          content:
            application/json:
              schema:
                type: object
                properties:
                  alteredRecordings:
                    type: array
                    default: []
                    items:
                      type: object
                      $ref: '#/components/schemas/Recording'
                    maxItems: 0
                    description: Altered records as an empty array
                  error:
                    type: string
                    description: A description of the error (invalid format or invalid syntax)
                    example: 'invalid_format'

components:
  schemas:
    Recording:
      properties:
        name:
          type: string
        content:
          type: string
      type: object
      example:
        name: 'nomFichierValide.sbs'
        content: 'MSG,5,1,4837,A4A445,18147,2016/12/09,09:13:34.120,2016/12/09,09:13:35.077,,7250,,,,,,,0,,0,0'
    OptionsAlteration:
      properties:
        haveLabel:
          type: boolean
        haveRealism:
          type: boolean
        haveNoise:
          type: boolean
        haveDisableLatitude:
          type: boolean
        haveDisableLongitude:
          type: boolean
        haveDisableAltitude:
          type: boolean
      type: object
      example:
        haveLabel: true
        haveRealism: true
        haveNoise: true
        haveDisableLatitude: true
        haveDisableLongitude: true
        haveDisableAltitude: true
