openapi: 3.0.0
info:
  title: ALTERATION SCENARIO API
  version: 2.0.0
servers:
  - url: http://localhost:3001
security:
  - ApiKeyAuth: []
paths:
  /recording/alteration:
    post:
      summary: Alterer un enregistrement
      description: Altere un enregistrement existant dans l'application
      requestBody:
        description: Représentation JSON de l'enregistrement à alterer
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenario:
                  type: string
                  description: Le scénario d'altération de l'enregistrement
                  example: 'hide all_planes at 2 seconds'
                recording:
                  type: object
                  $ref: '#/components/schemas/Recording'
                  description: L'enregistrement à alterer contenant un nom et un contenu de fichier
                recordingToReplay:
                  type: object
                  $ref: '#/components/schemas/Recording'
                  description: L'enregistrement à utiliser pour alterer recording contenant un nom et un contenu de fichier en cas de replay
              required:
                - scenario
                - recording
      responses:
        200:
          description: Enregistrement altéré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  alteredRecordings:
                    type: array
                    items:
                      type: object
                      $ref: '#/components/schemas/Recording'
                    description: Les enregistrements altérés sous forme de tableau
                  error:
                    type: string
                    nullable: true
                    example: null
        422:
          description: Format invalide ou erreur de syntaxe
          content:
            application/json:
              schema:
                type: object
                properties:
                  alteredRecordings:
                    type: array
                    default: []
                    items:
                      type: object
                      $ref: '#/components/schemas/Recording'
                    maxItems: 0
                    description: Les enregistrements altérés sous forme de tableau vide
                  error:
                    type: string
                    description: Une description de l'erreur (format invalide ou syntaxe invalide)
                    example: 'invalid_format'

components:
  schemas:
    Recording:
      properties:
        name:
          type: string
        content:
          type: string
      type: object
      example:
        name: 'nomFichierValide.sbs'
        content: 'MSG,5,1,4837,A4A445,18147,2016/12/09,09:13:34.120,2016/12/09,09:13:35.077,,7250,,,,,,,0,,0,0'
