services:
  #       $$$$$$$\                                                $$\                               $$\
  #       $$  __$$\                                               $$ |                              \__|
  #       $$ |  $$ | $$$$$$\   $$$$$$\   $$$$$$\  $$$$$$$\   $$$$$$$ | $$$$$$\  $$$$$$$\   $$$$$$$\ $$\  $$$$$$\   $$$$$$$\
  #       $$ |  $$ |$$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\ $$  __$$ |$$  __$$\ $$  __$$\ $$  _____|$$ |$$  __$$\ $$  _____|
  #       $$ |  $$ |$$$$$$$$ |$$ /  $$ |$$$$$$$$ |$$ |  $$ |$$ /  $$ |$$$$$$$$ |$$ |  $$ |$$ /      $$ |$$$$$$$$ |\$$$$$$\
  #       $$ |  $$ |$$   ____|$$ |  $$ |$$   ____|$$ |  $$ |$$ |  $$ |$$   ____|$$ |  $$ |$$ |      $$ |$$   ____| \____$$\
  #       $$$$$$$  |\$$$$$$$\ $$$$$$$  |\$$$$$$$\ $$ |  $$ |\$$$$$$$ |\$$$$$$$\ $$ |  $$ |\$$$$$$$\ $$ |\$$$$$$$\ $$$$$$$  |
  #       \_______/  \_______|$$  ____/  \_______|\__|  \__| \_______| \_______|\__|  \__| \_______|\__| \_______|\_______/
  #                           $$ |
  #                           $$ |
  #                           \__|

  alteration-install-server-dependencies:
    image: node:20-alpine
    container_name: alteration-install-server-dependencies
    volumes:
      - .:/app/packages
    working_dir: /app/packages/server
    entrypoint: npm install

  alteration-install-client-dependencies:
    image: node:20-alpine
    container_name: alteration-install-client-dependencies
    volumes:
      - .:/app/packages
    working_dir: /app/packages/client
    entrypoint: npm install

  alteration-build-server:
    image: node:20-alpine
    container_name: alteration-build-server
    volumes:
      - .:/app/packages
    working_dir: /app/packages/server
    entrypoint: npm run build
    depends_on:
      alteration-install-server-dependencies:
        condition: service_completed_successfully

  alteration-build-client:
    image: node:20-alpine
    container_name: alteration-build-client
    profiles:
      - production
    volumes:
      - .:/app/packages
    working_dir: /app/packages/client
    entrypoint: npm run build
    depends_on:
      alteration-install-client-dependencies:
        condition: service_completed_successfully

  alteration-migrate-db:
    image: node:20-alpine
    container_name: alteration-migrate-db
    profiles:
      - dev
    volumes:
      - .:/app/packages
    working_dir: /app/packages/server
    entrypoint: npm run migrate up
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/alterationdb
    depends_on:
      postgres:
        condition: service_healthy

  #       $$$$$$$$\                    $$\                                                   $$\
  #       \__$$  __|                   $$ |                                                  \__|
  #          $$ | $$$$$$\   $$$$$$$\ $$$$$$\          $$$$$$$\  $$$$$$\   $$$$$$\ $$\    $$\ $$\  $$$$$$$\  $$$$$$\   $$$$$$$\
  #          $$ |$$  __$$\ $$  _____|\_$$  _|        $$  _____|$$  __$$\ $$  __$$\\$$\  $$  |$$ |$$  _____|$$  __$$\ $$  _____|
  #          $$ |$$$$$$$$ |\$$$$$$\    $$ |          \$$$$$$\  $$$$$$$$ |$$ |  \__|\$$\$$  / $$ |$$ /      $$$$$$$$ |\$$$$$$\
  #          $$ |$$   ____| \____$$\   $$ |$$\        \____$$\ $$   ____|$$ |       \$$$  /  $$ |$$ |      $$   ____| \____$$\
  #          $$ |\$$$$$$$\ $$$$$$$  |  \$$$$  |      $$$$$$$  |\$$$$$$$\ $$ |        \$  /   $$ |\$$$$$$$\ \$$$$$$$\ $$$$$$$  |
  #          \__| \_______|\_______/    \____/       \_______/  \_______|\__|         \_/    \__| \_______| \_______|\_______/
  alteration-migrate-test-db:
    image: node:20-alpine
    container_name: alteration-migrate-test-db
    profiles:
      - test
      - e2e-test
    volumes:
      - .:/app/packages
    working_dir: /app/packages/server
    entrypoint: npm run migrate up
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-test:5432/alterationdb_test
    depends_on:
      postgres-test:
        condition: service_healthy

  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: alterationdb_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data-test:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

    #       $$$$$$$\                            $$\                                               $$\
    #       $$  __$$\                           $$ |                                              \__|
    #       $$ |  $$ | $$$$$$\   $$$$$$\   $$$$$$$ |       $$$$$$$\  $$$$$$\   $$$$$$\ $$\    $$\ $$\  $$$$$$$\  $$$$$$\   $$$$$$$\
    #       $$$$$$$  |$$  __$$\ $$  __$$\ $$  __$$ |      $$  _____|$$  __$$\ $$  __$$\\$$\  $$  |$$ |$$  _____|$$  __$$\ $$  _____|
    #       $$  ____/ $$ |  \__|$$ /  $$ |$$ /  $$ |      \$$$$$$\  $$$$$$$$ |$$ |  \__|\$$\$$  / $$ |$$ /      $$$$$$$$ |\$$$$$$\
    #       $$ |      $$ |      $$ |  $$ |$$ |  $$ |       \____$$\ $$   ____|$$ |       \$$$  /  $$ |$$ |      $$   ____| \____$$\
    #       $$ |      $$ |      \$$$$$$  |\$$$$$$$ |      $$$$$$$  |\$$$$$$$\ $$ |        \$  /   $$ |\$$$$$$$\ \$$$$$$$\ $$$$$$$  |
    #       \__|      \__|       \______/  \_______|      \_______/  \_______|\__|         \_/    \__| \_______| \_______|\_______/

  alteration-prod-server:
    build: .
    container_name: alteration-server-prod
    volumes:
      - .:/app/packages
    working_dir: /app/packages/server
    entrypoint: npm run start
    depends_on:
      alteration-build-server:
        condition: service_completed_successfully
    ports:
      - '3001:3001'

  alteration-prod-client:
    image: node:20-alpine
    container_name: alteration-client-prod
    volumes:
      - .:/app/packages
    working_dir: /app/packages/client
    entrypoint: npm run serve
    depends_on:
      alteration-build-client:
        condition: service_completed_successfully
      alteration-install-client-dependencies:
        condition: service_completed_successfully
    ports:
      - '3000:3000'
