name: Cypress Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]
        #  See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: packages/client/package-lock.json
      - name: Install dependencies client
        working-directory: packages/client
        run: npm ci
      - name: Install dependencies server
        working-directory: packages/server
        run: npm ci
      - name: Run client
        working-directory: packages/client
        run: npm run start &
      - name: Run server
        working-directory: packages/server
        run: npm run start &
      - name: Run test Client
        working-directory: packages/client
        run: npm test-cypress
