name: Java Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Copy fdit to .m2
        run: |
          mkdir -p $HOME/.m2/repository/com/fdit/
          cp -r packages/alteration/libs/com/fdit/tools $HOME/.m2/repository/com/fdit/

      - name: Build with Maven
        run: mvn --batch-mode --file packages/alteration/pom.xml --update-snapshots package
      - name: Run test Alteration
        working-directory: packages/alteration
        run: mvn test
