# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: packages/server/package-lock.json
    - name: Build
      working-directory: packages/server
      run: npm i
    - name: Run test Server
      working-directory: packages/server
      run : npm run test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tools-atc
        path: packages/alteration/libs/com/fdit/tools/tools-atc

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: testTools-atc
        path: packages/alteration/libs/com/fdit/tools/testTools-atc

    - name: Download artifacts and copy to .m2
      uses: actions/download-artifact@v3
      with:
        name: tools-atc
    - name : Creation repo
      run: mkdir -p $HOME/.m2/repository/com/fdit && tar xzf ${{ steps.download.outputs.download_path }} -C $HOME/.m2/repository/com/fdit/tools/
    - name: Extract downloaded artifact
      run: |
        mkdir -p $HOME/.m2/repository/com/fdit/tools/
        tar xzf ${{ steps.download.outputs.download_path }} -C $HOME/.m2/repository/com/fdit/tools/

    - name: Download and extract testTools artifacts
      uses: actions/download-artifact@v3
      with:
        name: testTools-atc

    - name: Extract downloaded artifact
      run: |
        mkdir -p $HOME/.m2/repository/com/fdit/tools/
        tar xzf ${{ steps.download-1.outputs.download_path }} -C $HOME/.m2/repository/com/fdit/tools/

    - name: Run test Alteration
      working-directory: packages/alteration
      run: mvn test

