name: Publish alteration on npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout your cod
      - name: Checkout
        uses: actions/checkout@v2
      # Publish client
      - name: Build and publish
        run: |
          cd packages/alteration-ts
          cp ../../.npmrc .npmrc
          npm version ${{ github.event.inputs.version }}
          npm i
          npm run build
          rm -rf docs src tests .gitignore .mocharc.json
          mv DApIA-Alteration-docs.md README.md
          mv build/* .
          rm -rf build
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
